version: "3"
services:
  start:
    build: .
    environment:
      - WEBSERVICE_PORT=4000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENV=dev
    volumes:
      - .:/usr/src/
    ports:
      - 80:4000
    command:
        - /bin/bash
        - -c
        - |
          python3 ./app.py
  redis:
    image: redis
    ports:
      - 6379:6379