apiVersion: v1
kind: Service
metadata:
  name: pysrv-service
spec:
  selector:
    app: my-deployment
  ports:
    - name: web
      port: 80
      targetPort: 4000
      nodePort: 30600
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-pod
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
