apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-pod
        image: nginx:latest
        ports:
        - name: web-port
          containerPort: 80
        volumeMounts:
        - name: nginx-conf-volume
          mountPath: /etc/nginx/conf.d
        livenessProbe:
          httpGet:
            path: /
            port: web-port
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 30  
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
