apiVersion: apps/v1
kind: Deployment
metadata:
  name: pysrv-deployment
  labels:
    app: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - name: pysrv
        image: lukeshih72/pysrv:latest
        env:
        - name: WEBSERVICE_PORT
          value: "4000"
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        ports:
        - name: webapp-port
          containerPort: 4000
        livenessProbe:
          httpGet:
            path: /
            port: webapp-port
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 30  
          successThreshold: 1
          failureThreshold: 3
